### ISSUE TITLE
It is not valid to include VK_KHR_portability_subset extension into the Vulkan specification

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Portability#18]
Vulkan specification has app compatibility guarantees that prohibit adding `VK_KHR_portability_subset` extension into the spec.

The problem is the extension demands the app to enumerate extensions and look for `VK_KHR_portability_subset`, otherwise the app could pick a non-conformant physical device without even knowing it is non-conformant (and of no fault of its own enter undefined behavior). Apps from before `VK_KHR_portability_subset` even existed cannot meet this requirement, so that makes the extension break Vulkan's backwards compatibility guarantees.

One way to fix this would be to mark this extension Instance, and introduce `VkInstanceCreateInfo::flags = VK_ENUMERATE_PORTABILITY_SUBSET_DEVICES`, that the app can use to explicitly opt-in to there being "non-conformant" devices in `vkEnumeratePhysicalDevices`. Another option would be to similarly have `pNext` or `flags` version of `vkEnumeratePhysicalDevices` that does the similar thing. Another option suggested was there being a Loader mechanism that makes the Loader also list non-conformant devices, though I find that impractical because some portability implementations should be treated as first-class citizens without a need for env variables.

(Issue forked from #14)

**Comment by lenny-lunarg** [comment]
After some discussions within the portability TSG, the feeling is that we need a new instance extension to deal with this. We intend to take the first approach you suggested, which is to add a flag at instance creation time to allow enumeration of devices that implement the portability subset. This extension will be implemented through the loader, much as you suggested at the end, but will use a proper API extension rather than an envar or similar. We are not changing the existing extension to an instance extension as we've found that mixing instance-level and device-level functionality causes all kinds of problems for the loader implementation. We're working this out, but it's in Khronos's internal repos right now, so I don't have anything to show here.

**Comment by KarenGhavam-lunarG** [comment]
The new extension to the loader, VK_KHR_portability_enumeration has been implemented in the loader ([Make portability drivers not load by default #924](https://github.com/KhronosGroup/Vulkan-Loader/pull/924)). The backward compatibility issue identified by this issue is now resolved.
