### ISSUE TITLE
Should VK_KHR_portability_subset be a device or instance extension?

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/Vulkan-Portability#25]
`VK_KHR_portability_subset` is a device extension, but is dependent on `VK_KHR_get_physical_device_properties2`, which is an instance extension.

[A concern has been raised](https://github.com/KhronosGroup/MoltenVK/issues/1363#issuecomment-842930603) that the app doesn't find out that `VK_KHR_portability_subset` is required until **_after_** it has created the instance and decided whether to enable `VK_KHR_get_physical_device_properties2`.

Should we move `VK_KHR_portability_subset` to be an instance extension, so that it can be detected at the time the app needs to decide whether to enable the prerequisite `VK_KHR_get_physical_device_properties2`?

**Comment by kvark** [comment]
I don't think this is necessary. We could just say that `VK_KHR_get_physical_device_properties2` is required, which means a Vulkan instance without this extension enabled would not see any portability devices whatsoever.

**Comment by lenny-lunarg** [comment]
I would hope that `VK_KHR_portability_subset` is dependent on either the `VK_KHR_get_physical_device_properties2` instance extension _or a Vulkan 1.1 device_. As long as this is true, I don't think there's a problem here. I'll also mention that we're working on an instance extension in the loader to preserve backwards compatibility so that an app will not see backwards-incompatible portability physical devices unless the app opts in. This extension has the extra benefit that the app will need to know at instance creation time if it will support portability implementations.

I definitely believe that `VK_KHR_portability_subset` **needs** to be a device extension. We made one instance extension that implements both instance-level and device-level behavior before (debug utils) and it was a terrible idea. An instance-level extension plus a device-level extension is more reasonable.

Also, if you're curious about my first sentence and why this sometimes depends on the instance and sometimes on the device, I'm happy to elaborate, but it won't be simple as we're getting into esoteric information about loader/ICD interfacing and mistakes that were made in the early days of Vulkan.

**Comment by billhollings** [comment]
As discussed at Vulkan portability meeting, `VK_KHR_portability_subset` needs to stay as a device extension. 

The requirement for checking for `VK_KHR_get_physical_device_properties2` only applies when using Vulkan 1.0, and since all portability implementations are planned for Vulkan 1.1 already, the scope of this is small.

Furthermore, LunarG is working on a separate instance extension for determining whether portability is expected on any particular implementation.

Consequently, this is resolved here, no changes are needed, and I'm closing this issue.

**Comment by MarkCallow** [comment]
> The requirement for checking for VK_KHR_get_physical_device_properties2 only applies when using Vulkan 1.0,

What about the requirement for _enabling_ it? I am using SDK 1.2.176.1 and until I did enable it I had a validation error when I later enabled portability and the application crashed.

**Comment by lenny-lunarg** [comment]
We don't expect to change the requirement to enable the extension. We do plan to eliminate the compability breakage in this use case by not showing portability devices by default (as I just outlined [here](https://github.com/KhronosGroup/Vulkan-Portability/issues/18#issuecomment-847350318)), however apps will still be required to enable the extension. This is consistent with the rest of Vulkan, where any device extension API that operates on `VkPhysicalDevice` handles may be used without enabling the extension, but any part of the extension which operates on `VkDevice`, `VkQueue`, or `VkCommandBuffer` handles requires that the extension be enabled.
